export const actionsTypes = {
    FETCH_ALL_CAR_REQUEST: 'FETCH_ALL_CARS_REQUEST',
    FETCH_ALL_CARS_SUCCESS: 'FETCH_ALL_CARS_SUCCESS',
    FETCH_ALL_CARS_FAILURE: 'FETCH_ALL_CARS_FAILURE',

    FETCH_CAR_REQUEST: 'FETCH_CAR_REQUEST',
    FETCH_CAR_SUCCESS: 'FETCH_CARS_SUCCESS',
    FETCH_CAR_FAILURE: 'FETCH_CARS_FAILURE',

    DELETE_CAR_REQUEST: 'DELETE_CAR_REQUEST',
    DELETE_CAR_SUCCESS: 'DELETE_CAR_SUCCESS',
    DELETE_CAR_FAILURE: 'DELETE_CAR_FAILURE',

    UPDATE_CAR_REQUEST: 'UPDATE_CAR_REQUEST',
    UPDATE_CAR_SUCCESS: 'UPDATE_CAR_SUCCESS',
    UPDATE_CAR_FAILURE: 'UPDATE_CAR_FAILURE',

    CAR_CREATE_REQUEST: 'CAR_CREATE_REQUEST',
    CAR_CREATE_SUCCESS: 'CAR_CREATE_SUCCESS',
    CAR_CREATE_FAILURE: 'CAR_CREATE_FAILURE',
};
